name: Build

on:
  push:
    branches:
      - python_spider

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Run Local Sonar Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: C:\tools\sonar-scanner\bin\sonar-scanner.bat